---
# tasks file for common
- name: Check wheteher netdata is installed if not install it
  script: files/netinstall.sh
  register: out

- debug: var=out.stdout_lines    
- name: Check whether netdata is and running
  systemd:
    state: started
    name: netdata

- name: Enable service to start at boot
  systemd:
    name: netdata
    enabled: yes 
        
- include: configure.yml
